{
 "title": "TeamSpeak 3 监控面板",
 "description": "Sample dashboard for GitHub project https://github.com/TilmannF/teamspeak-prometheus",
 "tags": [
  "prometheus",
  "teamspeak"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "数据源", "query": "prometheus" },
   {
    "name": "server_name",
    "label": "服务器名称",
    "query": "label_values(teamspeak_virtualserver_clientsonline, server_name)"
   },
   {
    "name": "virtualserver",
    "label": "虚拟服务器",
    "query": "label_values(teamspeak_virtualserver_clientsonline{server_name=~\"$server_name\"}, virtualserver_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "在线客户端详情",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(teamspeak_player_online{client_type!=\"1\"}) by (clid, cid, client_nickname, connection_client_ip, client_version, client_away, client_away_message, client_input_muted, client_output_muted, client_lastconnected, client_country)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "连接客户端数",
   "type": "stat",
   "description": "teamspeak_virtualserver_clientsonline - teamspeak_virtualserver_queryclientsonline",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(teamspeak_virtualserver_clientsonline{server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\",client_type!=\"1\"})"
    }
   ]
  },
  {
   "title": "最大客户端数",
   "type": "stat",
   "description": "Based on teamspeak_virtualserver_maxclients",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_maxclients{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "预留席位",
   "type": "stat",
   "description": "teamspeak_virtualserver_reserved_slots",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_reserved_slots{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "在线频道数",
   "type": "stat",
   "description": "Based on teamspeak_virtualserver_channelsonline",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_channelsonline{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "description": "teamspeak_virtualserver_uptime",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_uptime{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "实时在线人数",
   "type": "timeseries",
   "description": "Based on teamspeak_virtualserver_clientsonline & teamspeak_virtualserver_queryclientsonline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(teamspeak_virtualserver_clientsonline{server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\",client_type!=\"1\"})",
     "legendFormat": "Connected clients"
    }
   ]
  },
  {
   "title": "丢包率",
   "type": "timeseries",
   "description": "Based on teamspeak_virtualserver_total_packetloss_total, teamspeak_virtualserver_total_packetloss_speech, teamspeak_virtualserver_total_packetloss_keepalive, teamspeak_virtualserver_total_packetloss_control",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_total_packetloss_total{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "teamspeak_virtualserver_total_packetloss_speech{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}",
     "legendFormat": "Speech"
    },
    {
     "expr": "teamspeak_virtualserver_total_packetloss_keepalive{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}",
     "legendFormat": "Keepalive"
    },
    {
     "expr": "teamspeak_virtualserver_total_packetloss_control{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}",
     "legendFormat": "Control"
    }
   ]
  },
  {
   "title": "平均延迟",
   "type": "timeseries",
   "description": "Based on teamspeak_virtualserver_total_ping",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_total_ping{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"} ",
     "legendFormat": "Ping"
    }
   ]
  },
  {
   "title": "数据包速率",
   "type": "timeseries",
   "description": "Based on teamspeak_connection_packets_received_total, teamspeak_connection_packets_received_speech, teamspeak_connection_packets_received_keepalive, teamspeak_connection_packets_received_control, teamspeak_connection_packets_sent_total, teamspeak_connection_packets_sent_speech, teamspeak_connection_packets_sent_keepalive & teamspeak_connection_packets_sent_control",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(teamspeak_connection_packets_received_total{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming total"
    },
    {
     "expr": "irate(teamspeak_connection_packets_received_speech{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming speech"
    },
    {
     "expr": "irate(teamspeak_connection_packets_received_keepalive{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming keepalive"
    },
    {
     "expr": "irate(teamspeak_connection_packets_received_control{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming control"
    },
    {
     "expr": "-irate(teamspeak_connection_packets_sent_total{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing total"
    },
    {
     "expr": "-irate(teamspeak_connection_packets_sent_speech{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing speech"
    },
    {
     "expr": "-irate(teamspeak_connection_packets_sent_keepalive{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing keepalive"
    },
    {
     "expr": "-irate(teamspeak_connection_packets_sent_control{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing control"
    }
   ]
  },
  {
   "title": "实时带宽 (秒)",
   "type": "timeseries",
   "description": "Based on teamspeak_connection_bandwidth_received_last_second_total & teamspeak_connection_bandwidth_sent_last_second_total ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "teamspeak_connection_bandwidth_received_last_second_total{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"} * 8",
     "legendFormat": "Incoming"
    },
    {
     "expr": "-teamspeak_connection_bandwidth_sent_last_second_total{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"} * 8",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "实时带宽 (分)",
   "type": "timeseries",
   "description": "Based on teamspeak_connection_bandwidth_received_last_minute_total &  teamspeak_connection_bandwidth_sent_last_minute_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "teamspeak_connection_bandwidth_received_last_minute_total{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"} * 8",
     "legendFormat": "Incoming"
    },
    {
     "expr": "-teamspeak_connection_bandwidth_sent_last_minute_total{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"} * 8",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "连接流量详情",
   "type": "timeseries",
   "description": "Based on teamspeak_connection_bytes_received_total, teamspeak_connection_bytes_received_speech, teamspeak_connection_bytes_received_keepalive, teamspeak_connection_bytes_received_control, teamspeak_connection_bytes_sent_total, teamspeak_connection_bytes_sent_speech, teamspeak_connection_bytes_sent_keepalive, teamspeak_connection_bytes_sent_control",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "irate(teamspeak_connection_bytes_received_total{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming total"
    },
    {
     "expr": "irate(teamspeak_connection_bytes_received_speech{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming speech"
    },
    {
     "expr": "irate(teamspeak_connection_bytes_received_keepalive{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming keepalive"
    },
    {
     "expr": "irate(teamspeak_connection_bytes_received_control{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming control"
    },
    {
     "expr": "-irate(teamspeak_connection_bytes_sent_total{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing total"
    },
    {
     "expr": "-irate(teamspeak_connection_bytes_sent_speech{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing speech"
    },
    {
     "expr": "-irate(teamspeak_connection_bytes_sent_keepalive{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing keepalive"
    },
    {
     "expr": "-irate(teamspeak_connection_bytes_sent_control{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing control"
    }
   ]
  },
  {
   "title": "上传 / 下载速率",
   "type": "timeseries",
   "description": "Based on teamspeak_virtualserver_total_bytes_uploaded & teamspeak_virtualserver_total_bytes_downloaded",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(teamspeak_virtualserver_total_bytes_uploaded{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m])",
     "legendFormat": "Uploaded"
    },
    {
     "expr": "-irate(teamspeak_virtualserver_total_bytes_downloaded{server_name=~\"$server_name\",server_name=~\"$server_name\",virtualserver_name=~\"$virtualserver\"}[5m])",
     "legendFormat": "Downloaded"
    }
   ]
  }
 ]
}